# Generated by Django 5.1.5 on 2025-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
