# Generated by Django 6.0.1 on 2026-03-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
