# Generated by Django 6.0.1 on 2026-03-25 06:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_pickup_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='address',
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'display_name')},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='대표 사진'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/label_images/', verbose_name='빵+네임택 사진'),
        ),
        migrations.AddField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='정규화 상품명'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_price',
            field=models.PositiveIntegerField(verbose_name='할인가'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='품절 여부'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='original_price',
            field=models.PositiveIntegerField(verbose_name='원가'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_items', to='store.product'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='store.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('결제완료', '결제완료'), ('대기중', '대기중'), ('픽업완료', '픽업완료'), ('취소', '취소')], default='결제완료', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='AI 카테고리명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
